### ISSUE TITLE
Typo ct.00

### ISSUE THREAD

**Issue by SashankPilla** [v-xup6/MultilingualGH#1]
https://github.com/v-xup6/MultilingualGH/blob/3a6c557859f9965584b22c7e7a14650050313f1a/Languages/Chinese%20Traditional#L148

Possible Typo- `Reverse List`

**Comment by lin-ycv** [comment]
Good catch, fixed, thanks.
I'll keep the issue open for now in case you find some more, will close the issue after a few days.
